// World map: generated by a worker, with exploration fog-of-war, a rotating minimap and a full-screen map (M).
export class WorldMap {
  constructor({ seed, R = 4200, mpp = 12 }) {
    this.R = R; this.mpp = mpp; this.N = Math.ceil(2 * R / mpp); this.ready = false; this.progress = 0; this.wp = null; this.lastReveal = { x: 1e9, z: 1e9 };
    this.map = this.canvas(); this.fog = this.canvas(); const f = this.fog.getContext('2d'); f.fillStyle = 'rgba(28,22,14,.96)'; f.fillRect(0, 0, this.N, this.N);
    try { const s = localStorage.getItem('openworld.fog.' + seed + '.' + R); if (s) { const im = new Image(); im.onload = () => { f.globalCompositeOperation = 'source-over'; f.clearRect(0, 0, this.N, this.N); f.drawImage(im, 0, 0); }; im.src = s; } } catch { }
    this.seed = seed;
    const w = this.worker = new Worker(new URL('./map_worker.js', import.meta.url), { type: 'module' });
    w.onmessage = e => {
      const m = e.data; if (m.done) { this.ready = true; this.progress = 1; return; }
      this.map.getContext('2d').putImageData(new ImageData(m.data, m.N, m.rows), 0, m.y0); this.progress = (m.y0 + m.rows) / this.N;
    };
    w.postMessage({ seed, R, mpp });
    this.mini = document.getElementById('minimap'); this.big = document.getElementById('bigmap'); this.bigOpen = false; this.view = { x: 0, z: 0, zoom: 1 };
    this.setupBig(); this.saveT = 0;
  }
  // ---- named regions (deterministic, 800 m cells): the name depends on the terrain of the cell
  regionAt(x, z) {
    const S = 1400, cx = Math.floor(x / S), cz = Math.floor(z / S), key = cx + ',' + cz; this._reg ??= new Map();
    let r = this._reg.get(key); if (r) return r;
    const hash = (a, b, s) => { let h = Math.imul(a | 0, 374761393) ^ Math.imul(b | 0, 668265263) ^ Math.imul(s | 0, 2147483647); h = Math.imul(h ^ (h >>> 13), 1274126177); return ((h ^ (h >>> 16)) >>> 0) / 4294967296; };
    const mx = (cx + .5) * S, mz = (cz + .5) * S; let hs = 0, water = 0, n = 0;
    for (let i = -2; i <= 2; i++) for (let j = -2; j <= 2; j++) { const h = this.hfHeight ? this.hfHeight(mx + i * 150, mz + j * 150) : 20; hs += h; if (h < 0) water++; n++; }
    const avg = hs / n, pick = (a, s) => a[Math.floor(hash(cx, cz, s) * a.length)];
    const kind = avg > 50 ? ['Sierra', 'Altos', 'Páramo', 'Cumbres'] : water > 1 ? ['Ribera', 'Cañada', 'Remanso', 'Vega'] : avg > 18 ? ['Colinas', 'Bosque', 'Sierra Baja', 'Loma'] : ['Valle', 'Llanura', 'Pradera', 'Campiña'];
    const tail = ['del Cuervo', 'de los Pinos', 'del Lobo', 'Escondido', 'de las Nieblas', 'del Oro', 'del Halcón', 'de la Luna', 'Rojo', 'del Roble', 'del Águila', 'de la Aurora', 'del Viento', 'de las Sombras'];
    r = { name: `${pick(kind, 1)} ${pick(tail, 2)}`, cx, cz, x: mx, z: mz }; this._reg.set(key, r); return r;
  }
  // Roads (Path2D in map-pixel space, drawn between the terrain and the fog) and settlement icons.
  setPlan(plan) {
    this.places = plan.settlements; this.roadPaths = [[], [], []];
    for (const r of plan.roads) { const p = new Path2D(); r.pts.forEach(([x, z], i) => { const [px, pz] = this.toPx(x, z); i ? p.lineTo(px, pz) : p.moveTo(px, pz); }); this.roadPaths[r.kind].push(p); }
  }
  drawRoads(ctx, scalePx) {
    if (!this.roadPaths) return; ctx.lineCap = 'round'; ctx.lineJoin = 'round';
    for (const [kind, w, col] of [[2, 1.6, '#8a7048'], [1, 2.2, '#b08f58'], [0, 3, '#c8a468']]) { ctx.strokeStyle = col; ctx.lineWidth = Math.max(w, 2.2 / scalePx); for (const p of this.roadPaths[kind]) ctx.stroke(p); }
  }
  known(p) { if (p.type <= 1) return true; if (p._k === undefined || performance.now() - (p._kt || 0) > 2000) { p._k = this.discovered(p.x, p.z); p._kt = performance.now(); } return p._k; }
  discovered(x, z) { const [fx, fz] = this.toPx(x, z); return this.fog.getContext('2d').getImageData(Math.max(0, Math.min(this.N - 1, fx | 0)), Math.max(0, Math.min(this.N - 1, fz | 0)), 1, 1).data[3] < 200; }
  canvas() { const c = document.createElement('canvas'); c.width = c.height = this.N; return c; }
  toPx(x, z) { return [(x + this.R) / this.mpp, (z + this.R) / this.mpp]; }
  toWorld(px, pz) { return [px * this.mpp - this.R, pz * this.mpp - this.R]; }

  reveal(x, z, radius = 260) {
    if (Math.hypot(x - this.lastReveal.x, z - this.lastReveal.z) < 30) return; this.lastReveal = { x, z };
    const f = this.fog.getContext('2d'), [px, pz] = this.toPx(x, z), r = radius / this.mpp;
    f.globalCompositeOperation = 'destination-out'; const g = f.createRadialGradient(px, pz, r * .55, px, pz, r); g.addColorStop(0, 'rgba(0,0,0,1)'); g.addColorStop(1, 'rgba(0,0,0,0)');
    f.fillStyle = g; f.beginPath(); f.arc(px, pz, r, 0, 7); f.fill(); f.globalCompositeOperation = 'source-over';
  }
  persist(dt) { this.saveT += dt; if (this.saveT > 30) { this.saveT = 0; try { localStorage.setItem('openworld.fog.' + this.seed + '.' + this.R, this.fog.toDataURL('image/png')); } catch { } } }

  // ---- minimap: circular, rotates with the camera (forward = up)
  drawMini(px, pz, camYaw, size = 184) {
    const c = this.mini; if (!c || c.hidden) return; const ctx = c.getContext('2d'), dpr = Math.min(devicePixelRatio || 1, 2);
    if (c.width !== size * dpr) { c.width = c.height = size * dpr; c.style.width = c.style.height = size + 'px'; }
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0); ctx.clearRect(0, 0, size, size);
    const cx = size / 2, k = this.mpp * .42;                                              // .42 screen px per metre: the rim shows ~ 220 m
    const [mx, mz] = this.toPx(px, pz), fx = -Math.sin(camYaw), fz = -Math.cos(camYaw), alpha = -Math.PI / 2 - Math.atan2(fz, fx);
    ctx.save(); ctx.beginPath(); ctx.arc(cx, cx, cx - 3, 0, 7); ctx.clip();
    ctx.fillStyle = '#1b1610'; ctx.fillRect(0, 0, size, size);
    if (this.progress > 0) {
      ctx.translate(cx, cx); ctx.rotate(alpha); ctx.scale(k, k); ctx.translate(-mx, -mz); ctx.imageSmoothingEnabled = true;
      ctx.drawImage(this.map, 0, 0); this.drawRoads(ctx, k); ctx.drawImage(this.fog, 0, 0);
      for (const p of this.places || []) if (p.type <= 3 && this.known(p)) { const [qx, qz] = this.toPx(p.x, p.z); ctx.fillStyle = p.type === 0 ? '#ffd76a' : '#f1e6cc'; ctx.strokeStyle = '#1a1208'; ctx.lineWidth = 1 / k; ctx.beginPath(); ctx.arc(qx, qz, (p.type === 0 ? 5 : p.type === 1 ? 4 : 3) / k, 0, 7); ctx.fill(); ctx.stroke(); }
      for (const m of this.markers || []) { const [mx2, mz2] = this.toPx(m.x, m.z); ctx.fillStyle = m.color; ctx.strokeStyle = '#1a1208'; ctx.lineWidth = 1.2 / k; ctx.beginPath(); ctx.arc(mx2, mz2, 3.4 / k, 0, 7); ctx.fill(); ctx.stroke(); }
      if (this.wp) { const [wx, wz] = this.toPx(this.wp.x, this.wp.z); ctx.fillStyle = '#ff4d3d'; ctx.beginPath(); ctx.arc(wx, wz, 5 / k, 0, 7); ctx.fill(); ctx.strokeStyle = '#fff'; ctx.lineWidth = 1.5 / k; ctx.stroke(); }
    }
    ctx.restore();
    ctx.strokeStyle = '#d9b26a'; ctx.lineWidth = 3; ctx.beginPath(); ctx.arc(cx, cx, cx - 2, 0, 7); ctx.stroke();
    ctx.strokeStyle = 'rgba(0,0,0,.55)'; ctx.lineWidth = 1; ctx.beginPath(); ctx.arc(cx, cx, cx - 5, 0, 7); ctx.stroke();
    // player marker (always pointing up = camera forward) and compass letters
    ctx.fillStyle = '#fff'; ctx.strokeStyle = '#222'; ctx.lineWidth = 1.5; ctx.beginPath(); ctx.moveTo(cx, cx - 8); ctx.lineTo(cx + 6, cx + 7); ctx.lineTo(cx, cx + 3); ctx.lineTo(cx - 6, cx + 7); ctx.closePath(); ctx.fill(); ctx.stroke();
    ctx.font = 'bold 11px Georgia, serif'; ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
    for (const [l, vx, vy, col] of [['N', Math.sin(alpha), -Math.cos(alpha), '#ff6a52'], ['E', Math.cos(alpha), Math.sin(alpha), '#f3e2b8'], ['S', -Math.sin(alpha), Math.cos(alpha), '#f3e2b8'], ['O', -Math.cos(alpha), -Math.sin(alpha), '#f3e2b8']]) {
      const r = cx - 13; ctx.fillStyle = 'rgba(20,14,8,.75)'; ctx.beginPath(); ctx.arc(cx + vx * r, cx + vy * r, 8, 0, 7); ctx.fill(); ctx.fillStyle = col; ctx.fillText(l, cx + vx * r, cx + vy * r + .5);
    }
    if (this.wp) {                                                                              // waypoint distance
      const d = Math.hypot(this.wp.x - px, this.wp.z - pz); ctx.font = '11px Georgia, serif'; ctx.fillStyle = '#ffd9a0'; ctx.fillText(d > 1000 ? (d / 1000).toFixed(1) + ' km' : Math.round(d) + ' m', cx, size - 12);
    }
  }

  // ---- big map
  setupBig() {
    const c = this.big; if (!c) return; let drag = null;
    c.addEventListener('mousedown', e => { if (e.button === 0) drag = { x: e.clientX, y: e.clientY }; });
    addEventListener('mouseup', () => drag = null);
    addEventListener('mousemove', e => {
      if (!this.bigOpen) return; const r = c.getBoundingClientRect(); this.cursor = [e.clientX - r.left, e.clientY - r.top];
      if (drag) { const s = this.scale(); this.view.x -= (e.clientX - drag.x) / s; this.view.z -= (e.clientY - drag.y) / s; drag = { x: e.clientX, y: e.clientY }; }
    });
    c.addEventListener('wheel', e => { e.preventDefault(); const before = this.screenToWorld(e.offsetX, e.offsetY); this.view.zoom = Math.max(.3, Math.min(8, this.view.zoom * (e.deltaY < 0 ? 1.15 : 1 / 1.15))); const after = this.screenToWorld(e.offsetX, e.offsetY); this.view.x += before[0] - after[0]; this.view.z += before[1] - after[1]; }, { passive: false });
    c.addEventListener('contextmenu', e => { e.preventDefault(); const [x, z] = this.screenToWorld(e.offsetX, e.offsetY); this.wp = this.wp && Math.hypot(this.wp.x - x, this.wp.z - z) < 60 ? null : { x, z }; });
    c.addEventListener('dblclick', e => { const [x, z] = this.screenToWorld(e.offsetX, e.offsetY); this.wp = { x, z }; });
  }
  scale() { return this.view.zoom * Math.min(this.big.clientWidth, this.big.clientHeight) / (2 * this.R) * 1.6; }   // pixels per metre
  screenToWorld(sx, sy) { const s = this.scale(); return [this.view.x + (sx - this.big.clientWidth / 2) / s, this.view.z + (sy - this.big.clientHeight / 2) / s]; }
  openBig(px, pz) { this.bigOpen = true; this.view = { x: px, z: pz, zoom: 1.4 }; this.big.parentElement.classList.remove('hidden'); }
  closeBig() { this.bigOpen = false; this.big.parentElement.classList.add('hidden'); }
  drawBig(px, pz, camYaw) {
    if (!this.bigOpen) return; const c = this.big, dpr = Math.min(devicePixelRatio || 1, 2), W = c.clientWidth, H = c.clientHeight;
    if (c.width !== W * dpr || c.height !== H * dpr) { c.width = W * dpr; c.height = H * dpr; }
    const ctx = c.getContext('2d'); ctx.setTransform(dpr, 0, 0, dpr, 0, 0); ctx.fillStyle = '#211a11'; ctx.fillRect(0, 0, W, H);
    const s = this.scale(), k = s * this.mpp, ox = W / 2 - this.view.x * s, oz = H / 2 - this.view.z * s;
    ctx.save(); ctx.translate(ox - this.R * s, oz - this.R * s); ctx.scale(k, k); ctx.imageSmoothingEnabled = true; ctx.drawImage(this.map, 0, 0); this.drawRoads(ctx, k); ctx.drawImage(this.fog, 0, 0); ctx.restore();
    // grid every 500 m with labels
    ctx.strokeStyle = 'rgba(0,0,0,.22)'; ctx.lineWidth = 1; ctx.fillStyle = 'rgba(255,240,210,.75)'; ctx.font = '11px Georgia, serif'; ctx.textAlign = 'left';
    for (let v = -this.R; v <= this.R; v += 500) {
      const gx = ox + (v) * s, gz = oz + (v) * s; ctx.beginPath(); ctx.moveTo(gx, 0); ctx.lineTo(gx, H); ctx.moveTo(0, gz); ctx.lineTo(W, gz); ctx.stroke();
      if (gx > 30 && gx < W - 30) ctx.fillText((v / 1000).toFixed(1) + 'km', gx + 3, 14); if (gz > 30 && gz < H - 10) ctx.fillText((v / 1000).toFixed(1) + 'km', 4, gz - 3);
    }
    ctx.textAlign = 'center'; ctx.font = `italic ${Math.max(10, Math.min(19, 6 * this.view.zoom + 5))}px Georgia, serif`;
    const RG = Math.ceil(this.R / 1400);
    for (let cx = -RG; cx < RG; cx++) for (let cz = -RG; cz < RG; cz++) {
      const r = this.regionAt((cx + .5) * 1400, (cz + .5) * 1400), x = ox + r.x * s, z = oz + r.z * s; if (x < -100 || x > W + 100 || z < -20 || z > H + 20) continue;
      if (!r.at || performance.now() - r.at > 1500) { const [fx, fz] = this.toPx(r.x, r.z); r.alpha = this.fog.getContext('2d').getImageData(Math.max(0, Math.min(this.N - 1, fx | 0)), Math.max(0, Math.min(this.N - 1, fz | 0)), 1, 1).data[3]; r.at = performance.now(); }      // cached: readbacks are slow
      const a = r.alpha;
      ctx.fillStyle = `rgba(255,243,208,${a < 200 ? .85 : .25})`; ctx.strokeStyle = 'rgba(20,12,4,.8)'; ctx.lineWidth = 3; ctx.strokeText(r.name, x, z); ctx.fillText(r.name, x, z);
    }
    for (const p of this.places || []) {                                                       // settlements: city / towns always known, the rest once discovered
      if (!this.known(p)) continue; const x = ox + p.x * s, z = oz + p.z * s; if (x < -40 || x > W + 40 || z < -40 || z > H + 40) continue;
      const z0 = this.view.zoom, r = [9, 7, 5.5, 4, 4][p.type]; ctx.fillStyle = p.type === 0 ? '#ffd76a' : '#f4e9cf'; ctx.strokeStyle = '#1a1208'; ctx.lineWidth = 2; ctx.beginPath();
      if (p.type === 0) { for (let i = 0; i < 10; i++) { const a = -1.57 + i * .628, rr = i % 2 ? r * .5 : r; ctx.lineTo(x + Math.cos(a) * rr, z + Math.sin(a) * rr); } ctx.closePath(); } else if (p.type === 1) ctx.rect(x - r, z - r, r * 2, r * 2); else if (p.type === 4) { ctx.moveTo(x, z - r); ctx.lineTo(x + r, z + r); ctx.lineTo(x - r, z + r); ctx.closePath(); } else ctx.arc(x, z, r, 0, 7);
      ctx.fill(); ctx.stroke();
      if (p.type <= 1 || (p.type === 2 && z0 > 1.1) || (p.type >= 3 && z0 > 2.4)) { ctx.font = `${p.type <= 1 ? 'bold ' : ''}${p.type === 0 ? 15 : p.type === 1 ? 13 : 11}px Georgia, serif`; ctx.textAlign = 'center'; ctx.fillStyle = '#fff3d0'; ctx.strokeStyle = 'rgba(20,12,4,.9)'; ctx.lineWidth = 3; ctx.strokeText(p.name, x, z - r - 5); ctx.fillText(p.name, x, z - r - 5); }
    }
    if (this.progress < 1) { ctx.fillStyle = 'rgba(0,0,0,.6)'; ctx.fillRect(W / 2 - 110, 14, 220, 26); ctx.fillStyle = '#ffe6b0'; ctx.textAlign = 'center'; ctx.fillText('Dibujando el mundo… ' + Math.round(this.progress * 100) + '%', W / 2, 31); }
    for (const m of this.markers || []) {                                                        // NPC markers with names
      const x = ox + m.x * s, z = oz + m.z * s; ctx.fillStyle = m.color; ctx.strokeStyle = '#1a1208'; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(x, z, 5, 0, 7); ctx.fill(); ctx.stroke();
      if (this.view.zoom > 1.1 || m.always) { ctx.fillStyle = '#fff3d0'; ctx.font = '11px Georgia, serif'; ctx.textAlign = 'center'; ctx.fillText(m.label, x, z - 9); }
    }
    // waypoint
    if (this.wp) { const x = ox + this.wp.x * s + 0, z = oz + this.wp.z * s; ctx.fillStyle = '#ff4d3d'; ctx.strokeStyle = '#fff'; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(x, z); ctx.arc(x, z - 14, 7, Math.PI * .75, Math.PI * .25 + Math.PI * 2); ctx.closePath(); ctx.fill(); ctx.stroke(); }
    // player
    const pxs = ox + px * s, pzs = oz + pz * s, a = Math.atan2(-Math.cos(camYaw), -Math.sin(camYaw));
    ctx.save(); ctx.translate(pxs, pzs); ctx.rotate(a + Math.PI / 2); ctx.fillStyle = '#fff'; ctx.strokeStyle = '#111'; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(0, -12); ctx.lineTo(8, 10); ctx.lineTo(0, 5); ctx.lineTo(-8, 10); ctx.closePath(); ctx.fill(); ctx.stroke(); ctx.restore();
    // cursor coordinates
    if (this.cursor) { const [wx, wz] = this.screenToWorld(...this.cursor), h = this.hfHeight ? this.hfHeight(wx, wz) : null; ctx.textAlign = 'left'; ctx.fillStyle = 'rgba(0,0,0,.6)'; ctx.fillRect(10, H - 34, 230, 24); ctx.fillStyle = '#ffe6b0'; ctx.fillText(`x ${Math.round(wx)}  z ${Math.round(wz)}${h != null ? '  alt ' + Math.round(h) + ' m' : ''}`, 18, H - 18); }
  }
}
